### ISSUE TITLE
cannot find user by this audience

### ISSUE THREAD

**Issue by noname007** [jpush/jpush-api-php-client#10]
背景：
  使用的 easy push 样例，master key 和appkey 改成自己的。返回结果
"error": {"message": "cannot find user by this audience", "code": 1011}

**Comment by xiezefan** [comment]
Hello, 这应该是因为你调用API推送给某一个Tag, Alias或Registration, 但你的app并没有对用户设置对应的Tag, Alias, Registration. 所以系统提示你找不到用户.
你可以指定 `->setAudience(M\all)` 去推送给所有用户或者调用客户端API为特定用户设置Tag, Alias.
如果有问题可以联系我们的技术支持人员. http://docs.jpush.io/more/contact_us/
Ths.

**Comment by noname007** [comment]
但是，是有的用户出现了这个问题，有些用户没有问题。

**Comment by xiezefan** [comment]
@noname007 可能你对JPush Tag, Alias, RegistrationId 的使用方法上有一些误解. 你可以加 这个QQ群 384189223 我们的工作人员会帮你解答这方面的问题.  
: ) 
ths.
