### ISSUE TITLE
使用php sdk如何处理用户点击推送消息之后的事件

### ISSUE THREAD

**Issue by lifenglsf** [jpush/jpush-api-php-client#12]
推送使用的是php的sdk，现在想用户点击不同的推送消息跳转到不同的页面，要怎么处理

**Comment by xiezefan** [comment]
你好，PHP SDK只是负责将消息推送给设备。 如果想要你的设备实现“点击不同的推送消息跳转到不同的页面”。 需要客户端实现相关逻辑。 具体可以了解客户端处理JPush Notification/Message的基本概念。

你可以通过文档获取相关信息。 http://docs.jpush.io/
我更建议你加入我们的开发者群（445928015）中，我们的技术支持的同事可以帮你解决疑惑。 并且这一切都是免费的。
