### ISSUE TITLE
建议使用psr-4方式自动加载

### ISSUE THREAD

**Issue by zhao5908** [jpush/jpush-api-php-client#14]
files加载方式不是按需加载，建议改成psr-4方式按需加载。

按需加载只在需要的时候去加载，不会每个请求不管有没有用到都会加载用不到的文件。

```json
"autoload": {
        "psr-4": {
            "JPush\\": "src/JPush"
        }
    }
```

**Comment by xiezefan** [comment]
Hi，谢谢你的反馈，这段时间我正在重构PHP Server Client SDK，正是使用psr-4的规范去加载文件的。不过因为工作比较忙，重构工作进展比缓慢。不过您的建议很快就会新的SDK中见到了。 :)

**Comment by zhao5908** [comment]
即使您使用psr-0也请去除硬加载文件，实现按需加载。

**Comment by xiezefan** [comment]
@zhao5908 是的。 目前暂时无法实现按需加载。

因为我们作为一个公共类库，必须照顾到多种多样的开发者。所以我们的PHP SDK支持PHP5.1及以上的运行环境。

想要composer支持按需加载，需要使用到namespace，但是很遗憾的是假如在项目引入namespace的话，将导致php5.3及以下无法支持。

所以很遗憾我们暂时无法支持你的需求。

如果你有好的修改意见能解决问题，非常欢迎提交PR。

:)
