### ISSUE TITLE
Undefined index: X-Rate-Limit-Limit

### ISSUE THREAD

**Issue by zhuchaowe** [jpush/jpush-api-php-client#18]
jpush/jpush/src/JPush/core/JPushException.php :51

jpush/jpush/src/JPush/core/SchedulePayload.php :174

**Comment by zhuchaowe** [comment]
这个问题实在严重啊，PushPlayload里面也有报错，简直各种报错啊，快点修复下啊

**Comment by xiezefan** [comment]
@zhuchaowe 你好，感谢反馈问题。  
关于`Undefined index: X-Rate-Limit-Limit `这个错误，能提供更详细的异常栈吗？  

关于`PushPlayload里面也有报错` 这个问题，目前的设计是这样子的，只要你输入不合法的参数， JPush PHP Service SDK都会以抛出异常的方式警告开发者。 但我你看到的保存是否是这个问题，你能提供你构建PushPayload的报错信息吗？

**Comment by zhuchaowe** [comment]
首先JPush.php 的 134行
```
 list ($key, $value) = explode(': ', $line);
 $headers[$key] = $value;
```
我一发推送，推送是成功了，但是这里有时候会提示：undefined offset:1

还有下面这几个地方的地方，会报没有X-Rate-Limit-Limit，X-Rate-Limit-Remaining，X-Rate-Limit-Reset这几个key

jpush/jpush/src/JPush/core/JPushException.php :51
jpush/jpush/src/JPush/core/SchedulePayload.php :174
jpush/jpush/src/JPush/core/PushPayload.php :562

**Comment by xiezefan** [comment]
@zhuchaowe 恩，从错误上看，这的确是BUG。  

谢谢反馈。  

具体是什么情况下出现 `undefined offset:1` 错误，你能描述下吗？ 我看看能够重现下该问题。  

关于 `X-Rate-Limit-Limit，X-Rate-Limit-Remaining，X-Rate-Limit-Reset`  找不到，我大概了解到是什么原因了， 这两天会出一个版本Fix这个BUG。

**Comment by unidotnet** [comment]
undefined offset:1 错误 只要修改

Push.Php 133行或者134行

改成
`
if(!empty($line)) {
                        list ($key, $value) = explode(': ', $line);
                        $headers[$key] = $value;
                    }
`

就可以了，因为http response 会有一行空行，不能explode

@xiezefan 希望能更新到packagist.org , 这样以后composer update后就没问题了。

现在composer update 只能到3.3.1

**Comment by xiezefan** [comment]
@unidotnet  感谢提供解决方案，  composer已经update到最新的3.3.3版本。

**Comment by xiezefan** [comment]
已发布 [Version3.3.3]( https://github.com/jpush/jpush-api-php-client/releases/tag/v3.3.3 ) 解决此issue问题。   
:)

**Comment by zhuchaowe** [comment]
还有下面这几个地方的地方，会报没有X-Rate-Limit-Limit，X-Rate-Limit-Remaining，X-Rate-Limit-Reset这几个key

jpush/jpush/src/JPush/core/JPushException.php :51
jpush/jpush/src/JPush/core/SchedulePayload.php :174
jpush/jpush/src/JPush/core/PushPayload.php :562

-----

这几个地方还是会报错 这几个key

**Comment by xiezefan** [comment]
@zhuchaowe  HI， 你确定这是更新到最新版本(**当前为3.3.5**)测试的结果吗？ 我已经修复了这个问题。 麻烦你确认当前使用的版本然后再测试一下。

如果仍然有这个问题，麻烦Reopen这个issue。
