### ISSUE TITLE
3.3.6,Class APIConnectionException 无法直接use

### ISSUE THREAD

**Issue by liuzhaowei55** [jpush/jpush-api-php-client#22]
以后composer依赖后,错误类无法直接使用了需要手动引入文件,JPushException.php希望可以把这个文件里的两个类分开,然后添加到composer的autoload里;
PS:个人还是希望可以使用命名空间

**Comment by xiezefan** [comment]
你好，因为名空间是php5.3以后才支持的特性。为了兼容5.3以下版本，我们忍痛从系统中移除了与名空间相关的代码。

至于无法使用JPushException？我不太明白是什么意思，你是指你无法在你的逻辑里面的catch块使用JPushException吗？

**Comment by liuzhaowei55** [comment]
@xiezefan 恩,是的我通过require引入也无法使用
`Cannot redeclare class APIConnectionException`

**Comment by liuzhaowei55** [comment]
@xiezefan 
```
"autoload" : {
        "psr-0":{"jpush":"src/"},
        "files": [
            "src/JPush/JPush.php"
        ]

    }
```
能否把`JPushException.php`这个文件也添加到autoload里,这样composer也算是完整了可以use,
不过需要把这个文件里的两个类分开

**Comment by liuzhaowei55** [comment]
@xiezefan 不好意思,是我自己的问题,我可以直接`use APIConnectionException;`不需要因为文件了;
