### ISSUE TITLE
Protocol https not supported or disabled in libcurl

### ISSUE THREAD

**Issue by VictorSnow** [jpush/jpush-api-php-client#23]
PushPayload.php里面的常量 PUSH_VALIDATE_URL 前面多了一个空格, 在调试推送的时候会报错 Protocol https not supported or disabled in libcurl
是否目前禁止该API使用？

**Comment by xiezefan** [comment]
你好，感谢反馈。
这的确是我是写错了。Thanks
我已经release了一个版本 [Version3.3.7](https://github.com/jpush/jpush-api-php-client/releases/tag/v3.3.7) 来修复这个问题。
