### ISSUE TITLE
PHP版本低于5.5报Notice

### ISSUE THREAD

**Issue by leo108** [jpush/jpush-api-php-client#24]
Jpush.php:85用到了`CURL_SSLVERSION_TLSv1`，这个只有PHP >= 5.5才有定义，建议改成数字`1`

**Comment by SueYsok** [comment]
+1，或请在composer.json里注明依赖的php版本

**Comment by helperhaps** [comment]
@SueYsok 请问一般用的是php的哪个版本啊，考虑不支持太旧的版本，依赖的php版本将会在下一次发布的时候加上

**Comment by leo108** [comment]
@helperhaps 建议5.3或者5.4，对于SDK类型的代码来说，所依赖PHP版本太高不合适

**Comment by helperhaps** [comment]
@leo108 可以，方便的话，你可以按照你的想法提个pr

**Comment by xiezefan** [comment]
@leo108 @SueYsok   
  
Hi, 感谢反馈。  
  
[Version3.3.9](https://github.com/jpush/jpush-api-php-client/releases/tag/v3.3.9)已经修复了这个问题，你们可以更新下jpush的版本来解决这个问题。  
  
JPush PHP SDK 支持 PHP5.1以上的版本， 如果大家有好的建议，也可以提交PR给我们。  

Thanks ：）
