### ISSUE TITLE
setAudience('all')方法没有返回$this

### ISSUE THREAD

**Issue by sytlnrf** [jpush/jpush-api-php-client#25]
public function setAudience($all) {
        if (strtolower($all) === 'all') {
            $this->addAllAudience();
        } else {
            throw new InvalidArgumentException('Invalid audience value');
        }
    }

**Comment by helperhaps** [comment]
@sytlnrf 我刚刚接过这个项目，还没有仔细看过代码。刚刚大概看了一下这个地方，请问这个方法为什么需要返回一个 $this 呢

**Comment by xiezefan** [comment]
@helperhaps  为了可以链式调用

**Comment by helperhaps** [comment]
@xiezefan 可是都已经 setAudience 为 ’all‘ 了，这样的话还需要后续的链式调用吗？

**Comment by xiezefan** [comment]
@sytlnrf  
HI

谢谢你的反馈，最新的 [Version 3.4.1](https://github.com/jpush/jpush-api-php-client/releases/tag/v3.4.1) 已经解决了这个BUG
