### ISSUE TITLE
jpush.php里_request方法怀疑有bug

### ISSUE THREAD

**Issue by cfeibiao** [jpush/jpush-api-php-client#26]
原来的代码：
 curl_setopt($ch, CURLOPT_HTTPHEADER, array(
            'Content-Type: application/json',
            'Connection: Keep-Alive'
        ));
总是报这个错误：Basic authentication failed
后来我改成以下代码，就ok了：
 curl_setopt($ch, CURLOPT_HTTPHEADER, array(
            'Content-Type: application/json',
            'Connection: Keep-Alive',
            'Authorization: Basic ' . base64_encode($this->appKey . ":" . $this->masterSecret),
        ));

**Comment by xiezefan** [comment]
你好，代码JPush.php第86行

```
curl_setopt($ch, CURLOPT_USERPWD, $this->appKey . ":" . $this->masterSecret);
```

已经设置的apply与secret，所以你不需要额外设置。
请问你跑example的示例正常吗？

**Comment by conterspell** [comment]
// 设置headers
        /*
        curl_setopt($ch, CURLOPT_HTTPHEADER, array(
            'Content-Type: application/json',
            'Connection: Keep-Alive'
        ));
        */
        
        $base64=base64_encode("1bb81d808d69edc8a334dab8:ab980b3461bcde3e5fac1f85");
        curl_setopt($ch, CURLOPT_HTTPHEADER, array("Authorization:Basic $base64","Content-Type:application/json","Connection: Keep-Alive"));

**Comment by cfeibiao** [comment]
@xiezefan example的示例正常。是我自己创建了一个应用，但是客户端还没接入，服务端调用的时候报了“Basic authentication failed”

**Comment by xiezefan** [comment]
OK， 你按照示例替换掉Appkey和Secret就可以了。
验证失败应该是你调用的时候有问题。如果方便可以贴一下你初始化与调用的代码。我帮你看一下。

**Comment by cfeibiao** [comment]
问题已解决了，CURLOPT_HTTPHEADER是不用加这句'Authorization: Basic ' . base64_encode($this->appKey . ":" . $this->masterSecret),
谢谢各位
