### ISSUE TITLE
为啥还都使用files来加载类，jpush又不是每次请求都需要用，为啥不用psr4进行加载？

### ISSUE THREAD

**Issue by Clarence-pan** [jpush/jpush-api-php-client#30]

**Comment by helperhaps** [comment]
你好，这个问题我也注意到了，看关掉的 issue 中也有好多人在问。 至于为什么这么做，之前的维护人员说是为了兼容 5.3 以前的版本。

我的计划是，以 5.3.3 为界限，将项目分成两个，以前的版本基本不再进行维护以督促其升级，5.3.3 之后的版本提供 composer 的支持，你可以看看 dev 分支的最新代码，过一段时间会有一个比较大的升级。

**Comment by Clarence-pan** [comment]
soga，期待新版本ing...

**Comment by helperhaps** [comment]
@Clarence-pan  So dei su yo nei :smiley:

**Comment by helperhaps** [comment]
@Clarence-pan 已发布 v3.5.0

**Comment by Clarence-pan** [comment]
@helperhaps tks.

**Comment by helperhaps** [comment]
@Clarence-pan 但好多人都不用 Composer  直接下载使用 :sob: 我还不知道怎么就解决

**Comment by Clarence-pan** [comment]
@helperhaps  这确实是个问题。很多PHPer还都不习惯使用composer。我觉得可以为这些人单独提供一个autoloader

**Comment by helperhaps** [comment]
@Clarence-pan 唉，明明有更先进的方式却不跟进使用。ps：我已经提供了 autoload 文件了。
