### ISSUE TITLE
 Cannot declare class DevicePayload, because the name is already in use

### ISSUE THREAD

**Issue by tomhaoye** [jpush/jpush-api-php-client#31]
laravel框架使用composer安装，在执行clear-compiled过程报错

**Comment by helperhaps** [comment]
你好，这个问题属于 SDK 的遗留问题，为了兼容 5.3 以下的版本。你可以查看 dev 分支的代码，我们正在着手修复，使用 namespace 和 prs-4 ，并将代码以 5.3.3 为界线进行分开，对于以下版本不再提供支持，这样就可以避免很多麻烦。当然 dev 分支的代码还不是很稳定，请不要用于生产环境。

**Comment by tomhaoye** [comment]
好的，谢谢了。

**Comment by peablog** [comment]
建议没解决的问题不要close了。。

**Comment by helperhaps** [comment]
@peablog 也好，等发布了新的版本之后再关。

**Comment by jasonz1987** [comment]
出现了同样的问题，通过composer remove jpush 也无法移除？

**Comment by tomhaoye** [comment]
@jasonz1987 
我记得我是用remove移除了

**Comment by helperhaps** [comment]
@jasonz1987  这个嘛，貌似 3.4.3 版本已经修复这个问题了，理应可以正常的 remove。如果没有直接删除 vendor 目录下的相关文件夹和配置文件中的相关行就行了。

**Comment by jasonz1987** [comment]
@helperhaps   嗯 刚换到新版本了 不过貌似 READNE 文档里还没更新，写的还是3.4.2

**Comment by helperhaps** [comment]
@jasonz1987 这个是我们的疏忽，一般来讲 README 直接写默认的最新版本就行了。

**Comment by helperhaps** [comment]
@tomhaoye @peablog 发布了新版 v3.5.0

**Comment by tomhaoye** [comment]
👌

**Comment by helperhaps** [comment]
@tomhaoye 如果使用过程中发现任何问题欢迎提 Issue 出来讨论，我会第一时间回复。另外 JPush 相关的其他问题也可以在[极光社区](http://community.jiguang.cn/)发帖提问。

**Comment by tomhaoye** [comment]
get√
