### ISSUE TITLE
push_example.php根本无法运行啊

### ISSUE THREAD

**Issue by jmolboy** [jpush/jpush-api-php-client#32]
我设置了example里的appkey和secret但是运行后还是认证出错：

Fatal error: Uncaught exception 'APIRequestException' with message 'authen failed' in /JPush/core/PushPayload.php:578 Stack trace: #0

**Comment by helperhaps** [comment]
这个，认证错误一般都是自己的 appkey 和 master_secret 的问题

**Comment by jmolboy** [comment]
之前版本的key和master_secret能直接迁移到新的sdk上不？

**Comment by jmolboy** [comment]
Fatal error: Uncaught exception 'APIRequestException' with message 'cannot find user by this audience' in  /JPush/core/PushPayload.php:578

这个版本的是所有不匹配的调用都是以exception返回么

**Comment by helperhaps** [comment]
看代码是几乎所有非 200 的返回全部抛了异常，不过一般你

**Comment by jmolboy** [comment]
好的好的；多谢了

**Comment by helperhaps** [comment]
不过由于这个异常出现的次数太多，我会考虑在下一个重大的重构版本中让 SDK 进行捕获
