### ISSUE TITLE
jpush-api-php-client-3.5.0中引入JPush.php问题

### ISSUE THREAD

**Issue by zhouAndy** [jpush/jpush-api-php-client#34]
在这个版本的文档说明中，引用的是../src/JPush/JPush.php文件。想问一下，这个文件在哪里？还是说文档没有更新，已经换成Client.php，为什么examples没有更新？

**Comment by zhouAndy** [comment]
是官方的PHP版文档说明。引用的文件还是我刚说才的那个。我换成了Client.php是可以的，但报了一个”Fatal error: Class 'JPush\Config' not found in D:\wwwroot\system\plugin\JPush\Client.php on line 15“的错误。不明白为什么会这样

**Comment by helperhaps** [comment]
试这样的，官方文档的更新可能会有些许延迟，我会跟相关人员反映的。你可以按照 Github 上 README 来做。

PS：**尝试使用一下 Composer  吧**

**Comment by zhouAndy** [comment]
除此（Composer)没有别的办法了么？

**Comment by helperhaps** [comment]
@zhouAndy 请看 README ，那只是 PS 而已啊，不过墙猎推荐，不

**Comment by zhouAndy** [comment]
看完了，对我没有什么实质性的帮助啊。和Github项目下面的一段没什么差别啊。不懂SDK的目录结构都未改变，为何会找不到这个文件。

**Comment by helperhaps** [comment]
@zhouAndy 你要是用 Composer 就不会出现这个问题了 :smile: 

另一种解决办法是你下载 Github 上的源代码，再试一次就行了，github 上的代码比官网多了一个文件。至于为何找不到这个文件，那是因为没有加载到执行路径中，因为是用 Composer 来加载的。

**Comment by zhouAndy** [comment]
..这是强行安利Composer的节奏。。。我想说，我本身拿得文件就是从GitHub上下的。然后把src/JPush目录放到了我的plugin目录下面去了

**Comment by helperhaps** [comment]
我觉得 PHP 不用 Compsoer 就是耍流氓 :baby_chick: 你这样那肯定不行，话说你到底有没有看过README

> https://github.com/jpush/jpush-api-php-client#直接下载源码安装

Compsoer 可以成吨的提高你的配置效率

**Comment by zhouAndy** [comment]
我是Python开发者，偶尔用下PHP。只为解决一个问题，弄一大堆东西，肯定是超出我预期的。我知道你有情怀。但我的条件不允许我弄得那么正式。

**Comment by helperhaps** [comment]
这么巧，我 Ruby， 我的意思是用 Composer 可以解决这些配置上的问题，少踩很多坑，正因为你写 Python 可以用 pip 管理第三方包和依赖，而对应到 PHP 那就是 Compsoer 了。当然了，你不用，我也提供了相应的方式。

**Comment by helperhaps** [comment]
@zhouAndy 大兄弟，问题搞定了吗
