### ISSUE TITLE
有针对iOS10的mutable-content参数的设置方法吗？

### ISSUE THREAD

**Issue by moonfunjohn** [jpush/jpush-api-php-client#37]
有针对iOS10的mutable-content参数的设置方法吗？极光后台可以配置发送，找了一下API文档好像没有

**Comment by helperhaps** [comment]
这个嘛，由于我不是客户端开发的，所以不太清楚是什么，在文档中也没有看到相关描述，所以 SDK 中暂时是没有设置方法的，不过 IOS 10 的特性现在都在跟进中，相信很快就会有结论了。

**Comment by Percy0016** [comment]
有的 使用方法与 content available类似 参考链接
https://docs.jiguang.cn/jpush/server/push/rest_api_v3_push/#notification

**Comment by helperhaps** [comment]
@Percy0016 :+1:  我搜索了一圈没有找到，既然文档上有了，那我们 SDK 基本上马上会支持的

**Comment by helperhaps** [comment]
@moonfunjohn @Percy0016  如果是和 content-available 一样的设置的话，两位有人有兴趣提个 PR 吗

**Comment by helperhaps** [comment]
@moonfunjohn @Percy0016 现在已经发布最新的版本 v3.5.3 支持了 IOS 10 的新特性，composer 源，可能会有一些延迟，github 已经可以看到最新版了，如果有问题，请另开 issue 讨论
