### ISSUE TITLE
PHP Parse error:  syntax error

### ISSUE THREAD

**Issue by runphp** [jpush/jpush-api-php-client#38]
PHP Parse error:  syntax error, unexpected '=' in version.php

**Comment by helperhaps** [comment]
@runphp 额，这个问题我知道了，请问你是怎么安装的

**Comment by runphp** [comment]
@helperhaps composer install

**Comment by helperhaps** [comment]
@runphp 哈，那是我的锅，新增了一个 version.php 文件用于声明 SDK 的版本，但是使用的却不是 PHP 的常量定义语法，所以测试和示例跑得时候是 OK 的，感谢你第一时间提出来哈。
