### ISSUE TITLE
希望 SDK 能抄送推送

### ISSUE THREAD

**Issue by GuoDapeng** [jpush/jpush-api-php-client#44]
场景是这样的，一般开发可能是开发自己的项目。
但是向我们这种敏捷开发的小公司，一般会采取，只要消费较小的东西，我们自己准备好，能够快速给客户原型，甚至是已经开始运营的产品。
所以我们在项目交付之前可能已经有了一部分用户，我们一般也不希望这部分用户被放弃。
但是我们还要交接给甲方运维，用甲方自己的帐号。
而商店审核、用户更新的周期一般比较长。
所以，如果能同时给两个不同 AppKey 发送消息就方便多了。

我不知道有这需求的多不多。

**Comment by GuoDapeng** [comment]
我错了，我知道为啥了。对不起，我错了？

**Comment by helperhaps** [comment]
啥？极光推送设计上是不支持两个 appkey 的，不过按照你的情况来说的话，你一开始就只用一个 APPKEY 不就行了？这有其他难度么

ps： 只要你理解使用好推送的 audience ，可以作出表面上类似于两个 APPKEY 的假象

**Comment by GuoDapeng** [comment]
@helperhaps 我知道错了。早上起来还没睡醒。T_T

**Comment by helperhaps** [comment]
OK
有关极光的任何问题都可以来[极光社区](http://community.jiguang.cn/)提问，只要在工作日，回复速度都是有保证的

**Comment by GuoDapeng** [comment]
@helperhaps 这东西赶紧关了吧，太丢人了。谢谢
