### ISSUE TITLE
当接口挂的时候sdk crash

### ISSUE THREAD

**Issue by wyzhcn** [jpush/jpush-api-php-client#46]
key_exists() expects parameter 2 to be array, null given

trace 如下图
<img width="769" alt="2017-02-14 2 53 30" src="https://cloud.githubusercontent.com/assets/1079779/22919130/f37346ea-f2c8-11e6-8730-07c28c65d435.png">

**Comment by helperhaps** [comment]
看这信息，你的意思是在这种情况下 $body 的值是 null 吗？一般来讲处理不成功的时候都会有返回值的吧，请问你用的是那个 API 和什么情况下发生的这种错误

**Comment by wyzhcn** [comment]
看我贴图中的body内容，应该是你们极光的api出现502的时候会这样

**Comment by helperhaps** [comment]
贴一下你的 pushpayload 或者你的请求体

**Comment by wyzhcn** [comment]
<img width="1061" alt="_2017-02-14_ 3_58_13" src="https://cloud.githubusercontent.com/assets/1079779/22920319/7d047ff4-f2cf-11e6-8275-5425c19d6643.png">

**Comment by helperhaps** [comment]
@wyzhcn 当格式化 $body 之后，如果 $body 为 null 的话，就说明极光的服务器本身除了问题，那么在这种情况下

```php
if(is_string($response['body'])) {
            $this->code = ' ';
            $this->message = $response['body'];
        } else {
            $body = json_decode($response['body'], true);
            if (key_exists('error', $body)) {
                $this->code = $body['error']['code'];
                $this->message = $body['error']['message'];
            } else {
                $this->code = $body['code'];
                $this->message = $body['message'];
            }
        }
```

这么处理你觉得如何呢

**Comment by wyzhcn** [comment]
我觉得可以抛出一个 ServiceNotAvaliable 的异常

**Comment by helperhaps** [comment]
你说的有点道理，但是这么做的话，每次请求 API 的时候就要多 try 一个异常了，还没有照顾到其他已写好的代码，并且按照现在的逻辑在异常中载抛一个异常感觉有点奇怪（那现在这个异常怎么办，除非去改动 http.php 这个文件，修改整个异常的逻辑，但是为了这个感觉有点不太值得）

**Comment by wyzhcn** [comment]
现在就是已经在抛出异常了，只是抛得是ErrorException这个基础异常

**Comment by helperhaps** [comment]
现在是在异常对象构造函数里面，需要在这里之前变成 ServiceNotAvaliable，不过好像其实工作量也不大，我觉得你说的很有道理，就按照你说的办吧，发布版本之后我会在这里 @ 你

**Comment by wyzhcn** [comment]
好的，感谢

**Comment by helperhaps** [comment]
出现这种问题是我们这边的失误才对

**Comment by helperhaps** [comment]
@wyzhcn 如果有空的话，可以帮我 review 一下 https://github.com/jpush/jpush-api-php-client/commit/64e6a24f842199b5d36068623dbd3f5e47edaa97

**Comment by Lris12J** [comment]
@wyzhcn hi，感谢你提出的bug，有一份好礼相送，不知可否提供一下你的email，我们工作人员联系你

**Comment by wyzhcn** [comment]
@helperhaps 👍 

@Lris12J 心领了

**Comment by helperhaps** [comment]
@wyzhcn 只求给出 review 意见，在线等:lol:

**Comment by wyzhcn** [comment]
@helperhaps 没啥问题
后期可以考虑封装出一个Response类来处理，结构会更清晰

**Comment by helperhaps** [comment]
有些东西已经定型之后很难去修改的，所以我都想着，要不要在下班时间重新写一个第三方版本了

**Comment by wyzhcn** [comment]
稳定更重要 😜

**Comment by helperhaps** [comment]
OK， 我去 release 一下，这个 issue 我就关了哈
