### ISSUE TITLE
Class 'JPush\ServiceNotAvaliable' not found

### ISSUE THREAD

**Issue by wyzhcn** [jpush/jpush-api-php-client#48]
class 没有正确引用

**Comment by helperhaps** [comment]
请说明一下使用情况，

**Comment by wyzhcn** [comment]
在 https://github.com/jpush/jpush-api-php-client/blob/master/src/JPush/Http.php 加一行 use JPush\Exceptions\ServiceNotAvaliable;

**Comment by helperhaps** [comment]
@wyzhcn 确实是这样子的，方便提个 PR 帮我完善一下子吗

**Comment by helperhaps** [comment]
fixed in https://github.com/jpush/jpush-api-php-client/commit/5999396cd3cb2c69b531107109ea8821de211cf8
