### ISSUE TITLE
notification和message有什么却别？

### ISSUE THREAD

**Issue by BarryShieh** [jpush/jpush-api-php-client#50]
`->androidNotification('Hello Android', array(
            'title' => 'hello jpush',
            // 'builder_id' => 2,
            'extras' => array(
                'key' => 'value',
                'jiguang'
            ),
        ))
        ->message('message content', array(
            'title' => 'hello jpush',
            // 'content_type' => 'text',
            'extras' => array(
                'key' => 'value',
                'jiguang'
            ),
        ))`
这个是example里的代码，不知道message是什么？和notification有什么区别？刚接触极光，求教

**Comment by helperhaps** [comment]
不知道的话，就先读一下极光推送的官方文档吧 https://docs.jiguang.cn/jpush/guideline/faq/#_8
