### ISSUE TITLE
Uncaught JPush\Exceptions\APIRequestException

### ISSUE THREAD

**Issue by Ucer** [jpush/jpush-api-php-client#51]
我本地的demo,运行不起来

`Fatal error: Uncaught JPush\Exceptions\APIRequestException -- [1004]: authen failed thrown in /srv/wwwroot/default/jpush/src/JPush/Http.php on line 130`

**Comment by helperhaps** [comment]
https://docs.jiguang.cn/jpush/server/push/rest_api_v3_push/#_12

青岛官方文档查询对应错误码
