### ISSUE TITLE
./jpush.log 这个文件生成在哪里？

### ISSUE THREAD

**Issue by dongkaipo** [jpush/jpush-api-php-client#52]
``` error_log(./jpush.log): failed to open stream: Permission denied ``` 报错，但是不知道./jpush.log在哪里生成，用的是Laravel框架。Composer 集成方式

**Comment by helperhaps** [comment]
https://github.com/jpush/jpush-api-php-client/blob/master/src/JPush/Client.php#L12

可以看看源码理解一下，这个文件到底在哪里是需要看具体环境的，如果不需要的话，可以在新建 JPushClient 的时候，给第三个参数赋值为 `null` 就不会产生这个文件了，或者传递自己设置的路径比如 `/var/log/jpush.log` 之类的都可以

**Comment by dongkaipo** [comment]
好的，已经解决，多谢
