### ISSUE TITLE
androidNotification中的category字段多了个“`”符号

### ISSUE THREAD

**Issue by LGC119** [jpush/jpush-api-php-client#54]
![image](https://user-images.githubusercontent.com/7828027/27324000-491c2d08-55d6-11e7-848f-222622d6b588.png)

**Comment by helperhaps** [comment]
@LGC119 是这边的问题，已经发布新版（v3.5.17），可以通过 composer 安装试下，由于镜像同步问题，实际上，国内的镜像可能需要延迟一些。
