### ISSUE TITLE
app_key does not exist

### ISSUE THREAD

**Issue by tallprince** [jpush/jpush-api-php-client#55]
I get response 'app_key does not exist'.
I looked at client.php and noticed that it doesn't encode auth string into base64.
I'm sure that this is an issue.

**Comment by ZAZA316** [comment]
Hello.
I am a WeChat professional.
I can help you anytime and I trust you with your photo.
My ID is "ZAZA" or "mch316".
Anytime you can contact me.
My email address: zaza316614@hotmail.com
