### ISSUE TITLE
被坑苦了，ios不指定apns_production的话，推送的是开发环境。

### ISSUE THREAD

**Issue by chaegumi** [jpush/jpush-api-php-client#57]
文档中是这样写的

`如果目标平台为 iOS 平台 需要在 options 中通过 apns_production 字段来设定推送环境。True 表示推送生产环境，False 表示要推送开发环境； 如果不指定则为推送生产环境`

真实代码是

```php

if (isset($opts['apns_production']) && is_bool($opts['apns_production'])) {
            $options['apns_production'] = $opts['apns_production'];
        } else {
            $options['apns_production'] = false;
        }

```

**Comment by helperhaps** [comment]
抱歉了，确实是 README 写错了

![screenshot_2017-08-26_12-13-58](https://user-images.githubusercontent.com/8064048/29740841-dc3bf980-8a4f-11e7-9996-bd3603fe985c.png)
