### ISSUE TITLE
我测试写一个错误的alias进行推送，肯定推送不了，但是我服务端PHP得捕获到这个错误啊

### ISSUE THREAD

**Issue by jameshuimin** [jpush/jpush-api-php-client#61]
问题是我这边怎么捕捉不到这个异常呢？
![7efb292d1840773b794015ad029c9d24](https://user-images.githubusercontent.com/8947321/31884452-a99d3df0-b7b2-11e7-95de-ff2d7705cb98.jpg)
![dc0442052421ec14ee238ada0c17235e](https://user-images.githubusercontent.com/8947321/31884503-df4cf26a-b7b2-11e7-90c2-66e3fefabeda.png)

**Comment by helperhaps** [comment]
是啊，那你捕获不就好了

**Comment by jameshuimin** [comment]
是最新版本。你没看清楚内容吗？问题是捕获不到啊，catch  那五个异常都捕获不到！！直接出错！！

**Comment by helperhaps** [comment]
**我看清楚了**

最新版本的目录文件中是没有 core 文件夹的

> 另外提 issue 自己列出自己的版本，而不是让别人来猜

**Comment by jameshuimin** [comment]
我用的就是最新的，没有core，我是在thinkphp中集成。

**Comment by jameshuimin** [comment]
php版本 7.1.*

**Comment by jameshuimin** [comment]
catch (Exception $e){只有这个可以捕获到错误.
问题是  这个alias错误不是应该从jpush中的异常捕获到吗？

**Comment by helperhaps** [comment]
你自己看你的第二张截图

**Comment by jameshuimin** [comment]
我一开始用的composer下载的好像不是最新版本的

**Comment by jameshuimin** [comment]
![image](https://user-images.githubusercontent.com/8947321/31923938-70ba2156-b843-11e7-8d01-13e707ca9dcc.png)

**Comment by jameshuimin** [comment]
![image](https://user-images.githubusercontent.com/8947321/31923989-d8e35d74-b843-11e7-8e2e-299516cfef87.png)

**Comment by helperhaps** [comment]
Composer 的知识你还是要自己补啊
