### ISSUE TITLE
jpush 如何清空所有的 tags

### ISSUE THREAD

**Issue by jacobcyl** [jpush/jpush-api-php-client#63]
php sdk 中如果调用 $client->device()->addTags($registration_id, null) 可以清空该设备下的所有tag 吗？

根据你们官方文档中的说明 https://docs.jiguang.cn/jpush/server/push/rest_api_v3_device/
>  tags: 支持add, remove 或者空字符串。当tags参数为空字符串的时候，表示清空所有的 tags；

**Comment by helperhaps** [comment]
这个之前确实没有注意到，已在最新的发布的版本中予以添加可查看 [README](https://github.com/jpush/jpush-api-php-client/blob/master/doc/api.md#device-api)
