### ISSUE TITLE
最新加的clearTags方法有明显的语法问题啊

### ISSUE THREAD

**Issue by hugtale** [jpush/jpush-api-php-client#65]
最新加的clearTags方法有明显的语法问题啊！！

![image](https://user-images.githubusercontent.com/7259708/34669859-bd0d72d6-f4ae-11e7-901d-d3df2cfca01e.png)

**Comment by helperhaps** [comment]
啊，确实有，php 的数组和 Ruby 的 symbol混了已发最新版修复
