### ISSUE TITLE
vendor/jpush/jpush/src/JPush/DevicePayload.php 变量名错误

### ISSUE THREAD

**Issue by ssrpanel** [jpush/jpush-api-php-client#67]
vendor/jpush/jpush/src/JPush/DevicePayload.php
第38行 ：registrationId 变量未定义

public function clearTags($registration_id) {
    $url = $this->client->makeURL('device') . $registrationId;
    return Http::post($this->client, $url, ['tags' => '']);
}

**Comment by helperhaps** [comment]
fixed v3.5.28
