### ISSUE TITLE
DEFAULT_LOG_FILE目录权限问题

### ISSUE THREAD

**Issue by AaronZjs** [jpush/jpush-api-php-client#71]
composer package
src/JPush/Config

class Config {
    const DISABLE_SOUND = "_disable_Sound";
    const DISABLE_BADGE = 0x10000;
    const USER_AGENT = 'JPush-API-PHP-Client';
    const CONNECT_TIMEOUT = 20;
    const READ_TIMEOUT = 120;
    const DEFAULT_MAX_RETRY_TIMES = 3;
    const DEFAULT_LOG_FILE = null;

请问       const DEFAULT_LOG_FILE = null;    ，默认是一个路径，而且是当前文件下的，一般安装，该目录不给权限，是不是默认给null更好一点呢？

**Comment by helperhaps** [comment]
这个真的是属于历史遗留问题了，你可以在初始化的时候传递一个 null 进去

**Comment by helperhaps** [comment]
请问还有疑问吗

**Comment by Marchccc** [comment]
没有了，谢谢！
